### ISSUE TITLE
unable to use Cavvis 

### ISSUE THREAD

**Issue by ANUJGAHLAWAT** [MediaLabProjects/CavVis#1]
Hello dear
I am getting an error in executing the CavVis program. The following line of dataStructures.h file. 
bool operator<(Point const & rhs) const{ return std::tie(coord.x, coord.y, coord.z) < std::tie(rhs.coord.x, rhs.coord.y, rhs.coord.z);}
error is 156 [Error] 'tie' is not a member of 'std'
There are other lines in other header files which are also showing errors. can you suggest to me an easy way to run this program? I want to find cavities among the different pdb files. Currently, I am using DEV c++ program to execute your file.

In advance thanks for the help

**Comment by mosqueteer** [comment]
Dear Tiago Simoes,
Can you have a look on this topic.
It seems that Cavvis has a bug.
Can you fix it?
Best,
Abel Gomes

**Comment by tiagomiguelcs** [comment]
Dear @ANUJGAHLAWAT,

It seems to me that you are missing libraries installed on your system, please check whether you have all the libraries required to run Cavvis (e.g., tuple c++ lib). Let me know if you continue to have issues.
